name: CI

on:
  pull_request_target:
    types: [ opened, reopened, ready_for_review, synchronize ]
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Run-Common-CI:
    uses: dm-vdo/vdo-org-actions/.github/workflows/ci.yaml@main
    with:
      logfile: logs-${{ github.event.repository.owner.login }}-${{ github.event.repository.name }}-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}
      run-public-build: false
      run-public-tests: false
      run-private-build: false
      run-private-tests: true
      private-tests-action: |
        git clone https://github.com/${{ github.event.repository.owner.login }}/vdo-devel.git
        cd vdo-devel/src
        make DMLINUX_SOURCE_DIR=${{ github.workspace }} dmlinux-jenkins
      private-tests-action-failure: |
        REPO=${{ github.repository }}
        REPO=${REPO//\//-}
        cp -a vdo-devel/logs /permabit/user/bunsen/artifacts/logs.`date +'%Y%m%d%H%M'`.$REPO.${{ github.event.pull_request.number }}
